### ISSUE TITLE
not working multiple directories in repository

### ISSUE THREAD

**Issue by hchemanchula** [intuit/intuit-spring-cloud-config-validator#2]
commits to sub folders in the repository are not working

**Comment by marcellodesales** [comment]
@hchemanchula I will take care of it...

**Comment by marcellodesales** [comment]
# Directory bug

* Created a directory with a file
* Getting the error 

`remote: IOError: [Errno 2] No such file or directory: '/tmp/f30a60ee192a1f22745386cc1f021a5ce718ca3e/idps/idps-config.sh'`

* Hee's the output using the local local setup

```console
$ BRANCH=develop ./test.sh
Warning: Permanently added '[172.28.110.65]:52311' (ECDSA) to the list of known hosts.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 301 bytes | 301.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: ##################################################
remote: ###### Spring Cloud Config Validator 1.1.0 #######
remote: ##################################################
remote: Processing commit=f30a60ee192a1f22745386cc1f021a5ce718ca3e ref=refs/heads/develop
remote: Traceback (most recent call last):
remote:   File "hooks/pre-receive", line 334, in <module>
remote:     (executationDirPath, validationIndex) = ShellExecution.run()
remote:   File "hooks/pre-receive", line 306, in run
remote:     currentDirPath = dirPath if dirPath else ExecutionContext.getCurrentDirPath()
remote:   File "hooks/pre-receive", line 83, in getCurrentDirPath
remote:     currentDirPath = Validator.processPreReceivehookFilesInGithub(base, commit)
remote:   File "hooks/pre-receive", line 243, in processPreReceivehookFilesInGithub
remote:     filePath = Validator.saveFileContent(fileName, content, contextDir)
remote:   File "hooks/pre-receive", line 197, in saveFileContent
remote:     with open(filePath, "w") as text_file:
remote: IOError: [Errno 2] No such file or directory: '/tmp/f30a60ee192a1f22745386cc1f021a5ce718ca3e/idps/idps-config.sh'
To 172.28.110.65:test.git
 ! [remote rejected] develop -> develop (pre-receive hook declined)
error: failed to push some refs to 'git@172.28.110.65:test.git'
```

**Comment by marcellodesales** [comment]
# Validation missing files in dirs

* Fixing the dir creation, I noticed that the validation is skipping any directory... Just looking at files in the current directory

```console
remote: ##################################################
remote: ###### Spring Cloud Config Validator 1.1.0 #######
remote: ##################################################
remote: Validating new branch... HHHEEEERRREEE
remote: Processing commit=48414f981d5fb044fcd19b6518d11b9683407016 ref=refs/heads/develop
remote: Processing file config_msaas_test_01-e2e.yml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Processing file config_msaas_test_01-prd.yml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Processing file config_msaas_test_01-dev.yml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Processing file idps/idps-config.sh to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Verifying if the DIR exists: /tmp/48414f981d5fb044fcd19b6518d11b9683407016/idps
remote: CREATING DIR FOR CONTEXT: /tmp/48414f981d5fb044fcd19b6518d11b9683407016/idps
remote: Processing file idps/idps.yaml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Verifying if the DIR exists: /tmp/48414f981d5fb044fcd19b6518d11b9683407016/idps
remote: Processing file config_msaas_test_01.yml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Processing file config_msaas_test_01-prf.yml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Processing file idps/common.sh to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Verifying if the DIR exists: /tmp/48414f981d5fb044fcd19b6518d11b9683407016/idps
remote: Processing file application.yml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
echo ""
remote: Processing file config_msaas_test_01-qal.yml to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: Processing file README.md to be saved at /tmp/48414f981d5fb044fcd19b6518d11b9683407016
remote: => Validating SHA 48414f981d5fb044fcd19b6518d11b9683407016
remote: Looking for files matching  ['*.json', '*.yaml', '*.yml', '*.properties']
remote: (v) File config_msaas_test_01-prd.yml is valid!
echo "Copy the current validator script to the data container"
remote: (v) File config_msaas_test_01-e2e.yml is valid!
remote: (v) File config_msaas_test_01-qal.yml is valid!
remote: (v) File config_msaas_test_01.yml is valid!
remote: (v) File application.yml is valid!
remote: (v) File config_msaas_test_01-dev.yml is valid!
remote: (v) File config_msaas_test_01-prf.yml is valid!
```

**Comment by marcellodesales** [comment]
* Solution

```console
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 52311 -i /Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/id_rsa_from_github_simulator_server" git push test develop -f
Warning: Permanently added '[172.28.110.65]:52311' (ECDSA) to the list of known hosts.
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 358 bytes | 358.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: ##################################################
remote: ###### Spring Cloud Config Validator 1.1.1 #######
remote: ##################################################
remote: Validating new branch...
remote: Processing commit=a67275c202a8d2d070e3cf19fe135815a4ad110b ref=refs/heads/develop
remote: => Validating SHA a67275c202a8d2d070e3cf19fe135815a4ad110b
remote: Filtering Spring Cloud Config Server's files:  ['**/*.json', '**/*.yaml', '**/*.yml', '**/*.properties']
remote: (v) File config_msaas_test_01-prd.yml is valid!
remote: (v) File config_msaas_test_01-qal.yml is valid!
remote: (v) File config_msaas_test_01.yml is valid!
remote: (v) File config_msaas_test_01-prf.yml is valid!
remote: (x) File idps/idps.yaml is invalid: [2:33: syntax error: mapping values are not allowed here]
remote: (v) File application.yml is valid!
remote: (v) File config_msaas_test_01-e2e.yml is valid!
remote: (x) File config_msaas_test_01-dev.yml is invalid: [13:4: syntax error: mapping values are not allowed here]```

**Comment by marcellodesales** [comment]
Fixed on PR #3

**Comment by marcellodesales** [comment]
@hchemanchula Thank u for the report... Will release a new version...

**Comment by hchemanchula** [comment]
@marcellodesales thank you for looking into it. Was there a docker image created with the updated source code already?

**Comment by marcellodesales** [comment]
@hchemanchula Yes, any time there's a release...

* https://github.com/intuit/intuit-spring-cloud-config-validator/releases/tag/v1.2.0
* https://hub.docker.com/r/intuit/intuit-spring-cloud-config-validator/tags (See the `v1.2.0` tag)
