### ISSUE TITLE
Pushing new directories fail with OError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by marcellodesales** [intuit/intuit-spring-cloud-config-validator#4]
# Problem

* Pushing a new directory fails with a file `idps/idps-config.sh`
> **NOTE**: `sh` files must NOT be considered
* Tested the same with `dir/file.json` the same way

# Logs

```console
# Directory bug

* Created a directory with a file
* Getting the error after creating the dir `idps` with a file `idps-config.sh`

`remote: IOError: [Errno 2] No such file or directory: '/tmp/f30a60ee192a1f22745386cc1f021a5ce718ca3e/idps/idps-config.sh'`

* Here's the output using the local setup

```console
$ BRANCH=develop ./test.sh
Warning: Permanently added '[172.28.110.65]:52311' (ECDSA) to the list of known hosts.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 301 bytes | 301.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: ##################################################
remote: ###### Spring Cloud Config Validator 1.1.0 #######
remote: ##################################################
remote: Processing commit=f30a60ee192a1f22745386cc1f021a5ce718ca3e ref=refs/heads/develop
remote: Traceback (most recent call last):
remote:   File "hooks/pre-receive", line 334, in <module>
remote:     (executationDirPath, validationIndex) = ShellExecution.run()
remote:   File "hooks/pre-receive", line 306, in run
remote:     currentDirPath = dirPath if dirPath else ExecutionContext.getCurrentDirPath()
remote:   File "hooks/pre-receive", line 83, in getCurrentDirPath
remote:     currentDirPath = Validator.processPreReceivehookFilesInGithub(base, commit)
remote:   File "hooks/pre-receive", line 243, in processPreReceivehookFilesInGithub
remote:     filePath = Validator.saveFileContent(fileName, content, contextDir)
remote:   File "hooks/pre-receive", line 197, in saveFileContent
remote:     with open(filePath, "w") as text_file:
remote: IOError: [Errno 2] No such file or directory: '/tmp/f30a60ee192a1f22745386cc1f021a5ce718ca3e/idps/idps-config.sh'
To 172.28.110.65:test.git
 ! [remote rejected] develop -> develop (pre-receive hook declined)
error: failed to push some refs to 'git@172.28.110.65:test.git'
```

# Solution

* Create the directory of files before saving the stream
* A clean validation of a `new branch` now shows  the information with dirs

* Created a dir with file `idps/idps.yaml`
* Pushed the new dir 

```console
+git remote remove test || true
remote: #####################################################
remote: ### Intuit Spring Cloud Config Validator 1.1.1 ####
remote: #####################################################
remote: Validating new branch...
remote: Processing commit=9d661175861154e6ebef737fad9d7ddcc4c47288 ref=refs/heads/marcello
remote: => Validating SHA 9d661175861154e6ebef737fad9d7ddcc4c47288
remote: Filtering Spring Cloud Config Server's files:  ['**/*.json', '**/*.yaml', '**/*.yml', '**/*.properties']
remote: (x) File idps/idps.yaml is invalid: [2:33: syntax error: mapping values are not allowed here]
remote: (v) File config_msaas_test_01.yml is valid!
remote: (v) File application.yml is valid!
remote: (x) File config_msaas_test_01-dev.yml is invalid: [13:4: syntax error: mapping values are not allowed here]
remote: (v) File config_msaas_test_01-prf.yml is valid!
remote: (v) File config_msaas_test_01-prd.yml is valid!
remote: (v) File config_msaas_test_01-e2e.yml is valid!
remote: (v) File config_msaas_test_01-qal.yml is valid!
To 172.28.110.65:test.git
 ! [remote rejected] marcello -> marcello (pre-receive hook declined)
error: failed to push some refs to 'git@172.28.110.65:test.git'```

**Comment by marcellodesales** [comment]
#5 Fixed this issue!
